MetaArguments:
  log_file_path: "gnn_quantile_pc1.log"
  node_file: "../data/dec_2024/vertices.csv"
  edge_file: "../data/dec_2024/edges.csv"
  target_file: "../data//dec_2024/targets.csv"
  processed_location: "../data/dec_2024/processed_pc1"
  weights_directory: "../data//dec_2024/weights_cf"
  target_col: "pc1"
  target_index_name: 'nid'
  target_index_col: 0
  edge_src_col: "src"
  edge_dst_col: "dst"
  index_col: 0
  encoder_dict:
    random: RNI
  is_scratch_location: true
  global_seed: 42

ExperimentArguments:
  exp_args:
    Q_GAT:
      model_args:
        model: "GAT"
        num_layers: 3
        hidden_channels: 256
        normalization: "BatchNorm"
        num_neighbors: [30, 30, 30]
        batch_size: 1024
        dropout: 0.1
        lr: 0.001
        epochs: 100
        runs: 3
        device: 0
        log_steps: 10
        prediction_dim: 3
        use_quantile_heads: true
        quantile_alpha: 0.1
      data_args:
        task_name: "node-regression"
        is_regression: true
        num_test_shards: 2
    Q_GCN:
      model_args:
        model: "GCN"
        num_layers: 3
        hidden_channels: 256
        normalization: "BatchNorm"
        num_neighbors: [30, 30, 30]
        batch_size: 1024
        dropout: 0.1
        lr: 0.001
        epochs: 100
        runs: 3
        device: 0
        log_steps: 10
        prediction_dim: 3
        use_quantile_heads: true
        quantile_alpha: 0.1
      data_args:
        task_name: "node-regression"
        is_regression: true
        num_test_shards: 2
    Q_SAGE:
      model_args:
        model: "SAGE"
        num_layers: 3
        hidden_channels: 256
        normalization: "BatchNorm"
        num_neighbors: [30, 30, 30]
        batch_size: 1024
        dropout: 0.1
        lr: 0.001
        epochs: 100
        runs: 3
        device: 0
        log_steps: 10
        prediction_dim: 3
        use_quantile_heads: true
        quantile_alpha: 0.1
      data_args:
        task_name: "node-regression"
        is_regression: true
        num_test_shards: 2
    Q_GATv2:
      model_args:
        model: "GATv2"
        num_layers: 3
        hidden_channels: 256
        normalization: "BatchNorm"
        num_neighbors: [30, 30, 30]
        batch_size: 1024
        dropout: 0.1
        lr: 0.001
        epochs: 100
        runs: 3
        device: 0
        log_steps: 10
        prediction_dim: 3
        use_quantile_heads: true
        quantile_alpha: 0.1
      data_args:
        task_name: "node-regression"
        is_regression: true
        num_test_shards: 2
